services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    image: project-dev:latest
    container_name: project-dev
    volumes:
      - ./:/work:delegated
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./init.vim:/home/ubuntu/.config/nvim/init.vim
      - nvim-data:/home/ubuntu/.local/share/nvim
    environment:
      - TZ=America/New_York
      - TERM=xterm-256color
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - "8000:8000"
      - "5173:5173"
    tty: true
    stdin_open: true
volumes:
  nvim-data:

