name: backend-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:rolling-desktop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: "pip"

      - name: Install Poetry (via pip)
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry --version

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ runner.os }}-python3-12-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-python3-12-

      - name: Install deps
        run: |
          poetry install --with dev --no-interaction --no-ansi --no-root

      - name: Lint (Black)
        run: poetry run black --check .

      - name: Lint (Flake8)
        run: poetry run flake8 --max-line-length=120 --exclude .env,.venv,venv . # TODO: sync this with quality plan and fix long line

      # TODO: uncomment this after static analysis is added
      # - name: Type check (mypy)
      #   run: mypy .

      - name: Pytest + coverage
        run: |
          poetry run pytest -q --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
