name: backend-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:rolling-desktop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Add custom directory to PATH
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install deps
        run: |
          poetry install --with dev --no-interaction --no-ansi --no-root

      - name: Lint (Black)
        run: poetry run black --check .

      - name: Lint (Flake8)
        run: poetry run flake8 --max-line-length=120 --exclude .env,.venv,venv . # TODO: sync this with quality plan and fix long line

      # TODO: uncomment this after static analysis is added
      # - name: Type check (mypy)
      #   run: mypy .

      - name: Pytest + coverage
        run: |
          poetry run pytest -q --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
